services:
  - type: web
    name: book-scheduler-service
    env: python
    plan: free
    buildCommand: cd scheduler && pip install -r requirements.txt
    startCommand: cd scheduler && uvicorn src.main:app --host 0.0.0.0 --port $PORT
    branch: main
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
    autoDeploy: true

  - type: web
    name: bookmarkers-service
    env: python
    plan: free
    buildCommand: cd bookmarker && pip install -r requirements.txt
    startCommand: cd bookmarker && uvicorn src.api:app --host 0.0.0.0 --port $PORT
    branch: main
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
    autoDeploy: true
