services:
  - type: web
    name: book-scheduler-service
    env: python
    plan: free
    buildCommand: cd scheduler && pip install -r requirements.txt
    startCommand: cd scheduler && uvicorn src.main:app --host 0.0.0.0 --port $PORT
    branch: main
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    autoDeploy: true

  - type: web
    name: bookmarkers-service
    env: python
    plan: free
    buildCommand: cd bookmarker && pip install -r requirements.txt
    startCommand: cd bookmarker && uvicorn src.main:app --host 0.0.0.0 --port $PORT
    branch: main
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    autoDeploy: true

  - type: web
    name: bookmarker-front
    buildCommand: echo done
    env: node
    plan: free
    buildCommand: cd bookmarker-front && npm install
    startCommand: cd bookmarker-front && npm start
    port: 3000
    pullRequestPreviewsEnabled: true